model_type: "tabllama"
hidden_size: 8
num_layers: 2
num_heads: 8
num_epochs: 300
learning_rate: 2.944012173140272e-05
file_path: "./multiple_scenario_data_fin2.xml"
batch_size: 32
col_dim: 5
use_augment_warp: true
use_random_noise: true
use_augment_swap: true
seed: 0
patience: 20
min_delta: 0.001
debug: false
train: false
infer: false
in_dist: false
test_swap: true
init_seq: 20
device: "cuda:5"
test: true
warp_limit: 20
load_path: "./configs/testswap/testswap_best_model.pth"
save_path: "./configs/testswap/testswap_best_model.pth"
seq_num_layers: 3
seq_num_heads: 8
intermediate_size: 2400
swap_prob: 0.05012396411300077
noise_std: 0.046114444550630455
noise_mean: 0




