model_type: "tabllama"
hidden_size: 4
num_layers: 2
num_heads: 4
num_epochs: 300
learning_rate: 2.491423889455553e-05
file_path: "./multiple_scenario_data_fin2.xml"
batch_size: 32
col_dim: 5
use_augment_warp: True
use_random_noise: True
use_augment_swap: True
seed: 0
patience: 15
min_delta: 0.001
debug: false
train: false
infer: false
in_dist: false
test_swap: false
init_seq: 1
device: "cuda"
test: true
load_path: "./training_results/tabllama_best_model.pth"
seq_num_layers: 3
seq_num_heads: 4
intermediate_size: 2400
swap_prob: 0.0083388429783301
noise_std: 0.022400575875951165
